content:
  - name: content-posts-aws
    label: aws.md
    type: file
    path: content/posts/aws.md
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
        required: true
        default: ""
      - name: description
        type: string
        default: ""
      - name: date
        type: date
        default: ""
      - name: author
        type: string
        default: ""
      - name: tags
        type: string
        list: true
        default: []
      - name: category
        type: string
        default: ""
  - name: content-posts-cloud-eng-guide
    label: cloud-eng-guide.md
    type: file
    path: content/posts/cloud-eng-guide.md
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
        required: true
        default: ""
      - name: description
        type: string
        default: ""
      - name: date
        type: date
        default: ""
      - name: author
        type: string
        default: ""
      - name: tags
        type: string
        list: true
        default: []
      - name: category
        type: string
        default: ""
  - name: content-posts-markdown_vscode
    label: markdown_vscode.md
    description: Discover three powerful Markdown features that go beyond basic
      formatting - HTML integration, escape characters, and flexible syntax
      options for more control over your documents.
    type: file
    path: content/posts/markdown_vscode.md
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
        required: true
        default: "Beyond the Basics: 3 Markdown Features You're Probably Not Using"
      - name: description
        type: string
        default: Discover three powerful Markdown features that go beyond basic
          formatting - HTML integration, escape characters, and flexible syntax
          options for more control over your documents.
      - name: date
        type: date
        default: 2026-01-17
      - name: author
        type: string
        default: ""
      - name: tags
        type: string
        list: true
        default:
          - markdown
          - vscode
          - formatting
          - html
          - documentation
          - writing
          - text-editor
          - productivity
      - name: category
        type: string
        default: Guide
  - name: content-projects-cloud-dashboard
    label: cloud-dashboard.md
    type: file
    path: content/projects/cloud-dashboard.md
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
        required: true
        default: ""
      - name: description
        type: string
        default: ""
      - name: date
        type: date
        default: ""
      - name: author
        type: string
        default: ""
      - name: tags
        type: string
        list: true
        default: []
      - name: category
        type: string
        default: ""
  - name: content-projects-terraform-30
    label: terraform-30.md
    description: A daily deep-dive into Infrastructure as Code. Follow my progress
      through 30 structured labs and state management exercises.
    type: file
    path: content/projects/terraform-30.md
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
        required: true
        default: 30 Days of Terraform
      - name: description
        type: string
        default: A daily deep-dive into Infrastructure as Code. Follow my progress
          through 30 structured labs and state management exercises.
      - name: date
        type: date
        default: 2024-01-01
      - name: author
        type: string
        default: Mohammad Faisal
      - name: tags
        type: string
        list: true
        default:
          - terraform
          - infrastructure-as-code
          - devops
          - cloud
          - automation
          - iac
      - name: category
        type: string
        default: Infrastructure
