media:
  - name: content-images
    label: images
    input: content/images
    output: /content/images
    extensions:
      - jpg
      - jpeg
      - png
      - webp
      - gif
      - svg
components: {}
content:
  - name: data
    label: data.json
    type: file
    path: data.json
    format: json
    fields:
      - name: title
        type: string
        required: true
      - name: description
        type: string
      - name: date
        type: date
      - name: author
        type: string
      - name: tags
        type: string
        list: true
      - name: category
        type: string
  - name: content-posts
    label: content/posts
    type: collection
    path: content/posts
    filename: "{year}-{month}-{day}-{primary}.md"
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
        required: true
      - name: description
        type: string
      - name: date
        type: date
      - name: author
        type: string
      - name: tags
        type: string
        list: true
      - name: category
        type: string
  - name: content-posts-terraform-30
    label: content/posts/terraform-30
    type: collection
    path: content/posts/terraform-30
    filename: "{year}-{month}-{day}-{primary}.md"
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
        required: true
      - name: description
        type: string
      - name: date
        type: date
      - name: author
        type: string
      - name: tags
        type: string
        list: true
      - name: category
        type: string
  - name: content-projects
    label: content/projects
    type: collection
    path: content/projects
    filename: "{year}-{month}-{day}-{primary}.md"
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
        required: true
      - name: description
        type: string
      - name: date
        type: date
      - name: author
        type: string
      - name: tags
        type: string
        list: true
      - name: category
        type: string
